"""empty message

Revision ID: 262484e4852
Revises: 1bbd7594eeb
Create Date: 2015-09-16 21:50:19.583723

"""

# revision identifiers, used by Alembic.
revision = '262484e4852'
down_revision = '1bbd7594eeb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about')
    ### end Alembic commands ###
