"""empty message

Revision ID: 26ebf2e3c80
Revises: None
Create Date: 2015-09-14 20:25:34.394158

"""

# revision identifiers, used by Alembic.
revision = '26ebf2e3c80'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('tumblr_key', sa.String(length=50), nullable=True),
    sa.Column('tumblr_secret', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
