"""empty message

Revision ID: 46ec1cf518a
Revises: 4dfabe325e7
Create Date: 2015-09-18 03:52:34.127190

"""

# revision identifiers, used by Alembic.
revision = '46ec1cf518a'
down_revision = '4dfabe325e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('position', sa.Integer(), nullable=True))
    op.drop_column('chapter', 'order')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('chapter', 'position')
    ### end Alembic commands ###
