"""empty message

Revision ID: 4dfabe325e7
Revises: 594f0629433
Create Date: 2015-09-18 03:30:20.817755

"""

# revision identifiers, used by Alembic.
revision = '4dfabe325e7'
down_revision = '594f0629433'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chapter', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chapter', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
