"""empty message

Revision ID: 59295bf3464
Revises: f52f051632
Create Date: 2015-09-17 00:24:49.921890

"""

# revision identifiers, used by Alembic.
revision = '59295bf3464'
down_revision = 'f52f051632'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('fandom_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('content_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('char_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('ship_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work')
    ### end Alembic commands ###
