"""empty message

Revision ID: 594f0629433
Revises: 1e325fc9b3f
Create Date: 2015-09-17 15:22:32.474545

"""

# revision identifiers, used by Alembic.
revision = '594f0629433'
down_revision = '1e325fc9b3f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('summary', sa.Text(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'summary')
    ### end Alembic commands ###
