"""empty message

Revision ID: f52f051632
Revises: 262484e4852
Create Date: 2015-09-16 23:40:06.211305

"""

# revision identifiers, used by Alembic.
revision = 'f52f051632'
down_revision = '262484e4852'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('modified_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'modified_at')
    op.drop_column('user', 'created_at')
    ### end Alembic commands ###
